# -*- coding: utf-8 -*-
"""IDX_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UHZtqZkD1YKEaa4vlxB9jeCSYliyYDXF

Week 2: Data Exploration
"""

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

import os
import glob
import re
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

search_pattern = "/content/drive/MyDrive/**/CRMLSSold*.csv"
files = glob.glob(search_pattern, recursive=True)

print("Total CRMLSSold files found:", len(files))

for f in files:
    print(f)

# Select only 2025-01 to 2026-05 files

selected_files = []

for f in files:
    filename = os.path.basename(f)
    match = re.search(r"(\d{6})", filename)

    if match:
        ym = match.group(1)
        if "202501" <= ym <= "202605":
            selected_files.append(f)

selected_files = sorted(selected_files, key=lambda x: re.search(r"(\d{6})", os.path.basename(x)).group(1))

print("Selected files:", len(selected_files))

for f in selected_files:
    print(os.path.basename(f))

# Load and combine all selected monthly files

dfs = []

for f in selected_files:
    filename = os.path.basename(f)
    ym = re.search(r"(\d{6})", filename).group(1)

    temp = pd.read_csv(f, low_memory=False)
    temp["source_file"] = filename
    temp["data_month"] = ym

    dfs.append(temp)

df_raw = pd.concat(dfs, ignore_index=True)

print("Raw data shape:", df_raw.shape)
df_raw.head()

# Check column names

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 200)

df_raw.columns.tolist()

# Filter required property type
# Project requirement: only use Residential + SingleFamilyResidence

df = df_raw[
    (df_raw["PropertyType"] == "Residential") &
    (df_raw["PropertySubType"] == "SingleFamilyResidence")
].copy()

print("After filtering:", df.shape)

# Select useful columns for Week 2 EDA

candidate_cols = [
    "ClosePrice",
    "LivingArea",
    "BedroomsTotal",
    "BathroomsTotalInteger",
    "BathroomsFull",
    "LotSizeSquareFeet",
    "YearBuilt",
    "City",
    "CountyOrParish",
    "PostalCode",
    "Latitude",
    "Longitude",
    "PropertyType",
    "PropertySubType",
    "data_month",
    "source_file"
]

existing_cols = [c for c in candidate_cols if c in df.columns]

df_eda = df[existing_cols].copy()

print("EDA data shape:", df_eda.shape)
df_eda.head()

# Standardize column names for easier analysis

df_eda["Bedrooms"] = df_eda["BedroomsTotal"] if "BedroomsTotal" in df_eda.columns else np.nan

if "BathroomsTotalInteger" in df_eda.columns:
    df_eda["Bathrooms"] = df_eda["BathroomsTotalInteger"]
elif "BathroomsFull" in df_eda.columns:
    df_eda["Bathrooms"] = df_eda["BathroomsFull"]
else:
    df_eda["Bathrooms"] = np.nan

df_eda["LotSize"] = df_eda["LotSizeSquareFeet"] if "LotSizeSquareFeet" in df_eda.columns else np.nan

# Convert numeric columns
# Note: errors="coerce" turns invalid values into NaN.

numeric_cols = [
    "ClosePrice",
    "LivingArea",
    "Bedrooms",
    "Bathrooms",
    "LotSize",
    "YearBuilt",
    "Latitude",
    "Longitude"
]

for col in numeric_cols:
    if col in df_eda.columns:
        df_eda[col] = pd.to_numeric(df_eda[col], errors="coerce")

# Basic cleaning for EDA
# Note: For Week 2, keep cleaning light. Do not over-process yet.

before = len(df_eda)

df_eda = df_eda[df_eda["ClosePrice"].notna()]
df_eda = df_eda[df_eda["ClosePrice"] > 0]

df_eda = df_eda[df_eda["LivingArea"].isna() | (df_eda["LivingArea"] > 0)]
df_eda = df_eda[df_eda["Bedrooms"].isna() | (df_eda["Bedrooms"] >= 0)]
df_eda = df_eda[df_eda["Bathrooms"].isna() | (df_eda["Bathrooms"] >= 0)]
df_eda = df_eda[df_eda["LotSize"].isna() | (df_eda["LotSize"] > 0)]

after = len(df_eda)

print("Rows before cleaning:", before)
print("Rows after cleaning:", after)
print("Rows removed:", before - after)

# Missing value summary

missing_summary = df_eda.isna().sum().sort_values(ascending=False).to_frame("missing_count")
missing_summary["missing_percent"] = missing_summary["missing_count"] / len(df_eda) * 100

missing_summary

# Summary statistics

eda_cols = ["ClosePrice", "LivingArea", "Bedrooms", "Bathrooms", "LotSize"]

df_eda[eda_cols].describe()

# Distribution plots required by Week 2

for col in eda_cols:
    plt.figure(figsize=(8, 5))
    df_eda[col].dropna().hist(bins=50)
    plt.title(f"Distribution of {col}")
    plt.xlabel(col)
    plt.ylabel("Count")
    plt.show()

# Log plots for skewed variables
# Note: ClosePrice and LotSize usually have extreme values.

for col in ["ClosePrice", "LotSize"]:
    plt.figure(figsize=(8, 5))
    np.log1p(df_eda[col].dropna()).hist(bins=50)
    plt.title(f"Distribution of log({col})")
    plt.xlabel(f"log({col})")
    plt.ylabel("Count")
    plt.show()

# Save Week 2 EDA file

RAW_DIR = os.path.dirname(selected_files[0])
BASE_DIR = os.path.dirname(RAW_DIR)
PROCESSED_DIR = os.path.join(BASE_DIR, "processed")

os.makedirs(PROCESSED_DIR, exist_ok=True)

eda_output_path = os.path.join(
    PROCESSED_DIR,
    "week2_crmls_202501_202605_eda.csv"
)

df_eda.to_csv(eda_output_path, index=False, encoding="utf-8")

print("Saved Week 2 EDA data to:")
print(eda_output_path)
print("Final shape:", df_eda.shape)
